---
title: "sentry-ravenからsentry-ruby移行時に気をつけること"
emoji: "🔖"
type: "tech" # tech: 技術記事 / idea: アイデア
topics: [sentry]
published: true
---

今まで Rails アプリケーションの Sentry クライアントとして`sentry-raven`という Gem を使わせてもらってました。
https://github.com/getsentry/sentry-ruby/tree/master/sentry-raven

その`sentry-raven`がメンテナンスモードになったため、最近`sentry-ruby`に移行しました。
https://github.com/getsentry/sentry-ruby

移行自体はドキュメントの通りに進めればそこまで大変ではないのですが、1 点ドキュメントには書いてない点で気をつけたほうがいいことがあったので共有できればと思います（正確には元々の使い方が悪かっただけなのですが...）。
https://docs.sentry.io/platforms/ruby/migration/

## capture_exception と capture_message の引数を見直そう

例えば移行前に下記のようなコードがあったとします。

```rb
begin
  1 / 0
rescue ZeroDivisionError => e
  Raven.capture_message(e)
end
```

上記のコードでエラーは出ないのですが、移行して`Raven.capture_message(e)` から `Sentry.capture_message(e)`に変更するとエラーが発生してしまいます。

```
ArgumentError: expect the argument to be a String, got ZeroDivisionError (#<ZeroDivisionError: divided by 0>)
```

## sentry-raven では capture_exception と capture_message がエイリアスメソッドだった

そもそも`capture_message`は Sentry にテキスト情報を送るメソッドなので引数に文字列を指定しないといけません。
https://docs.sentry.io/platforms/ruby/usage/#capturing-messages

ではなぜ`Raven.capture_message(e)`は引数に文字列を指定しなくても実行できていたのだろうと調べてると、
どうやら`capture_exception`と`capture_message`は両方`capture_type`のエイリアスメソッドだったため実行できたようです。
https://www.rubydoc.info/gems/sentry-raven/Raven%2FRack.capture_type
https://github.com/getsentry/sentry-ruby/blob/master/sentry-raven/lib/raven/integrations/rack.rb#L35

`capture_message`の引数が文字列ではなくても`capture_exception`の方の引数として解釈され、`capture_exception`メソッドとして動いていたみたいですね。

では`sentry-ruby`ではどうかというと、見た感じそれぞれ別個のメソッドとして独立していました。
なので移行した時にエラーが起きたと思われます。
https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry-ruby.rb#L292
https://github.com/getsentry/sentry-ruby/blob/master/sentry-ruby/lib/sentry-ruby.rb#L284

もしこれから`sentry-raven`から`sentry-ruby`に移行する方がいましたら、お気をつけくださいー！
